nombre=input("porfavor ingrese su nombre ")
apellido=input("porfavor ingrese su apellido ")
edad=input("porfavor ingrese su edad ")
direccion=input("porfavor ingrese su direccion ")
telefono=input("porfavor ingrese su numero de telefono ")
genero=input("porfavor ingrese su genero ")
print(nombre)
print(apellido)
print(edad)
print(direccion)
print(telefono)
print(genero)
